# Generated by Django 3.2.5 on 2021-07-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_clientcontact_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
