# Generated by Django 3.2.5 on 2021-07-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('main', '0004_alter_clientrequest_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrequest',
            options={'verbose_name': 'Заявка клиента', 'verbose_name_plural': 'Заявки клиентов'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Страховое предложение', 'verbose_name_plural': 'Страховые предложения'},
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='patronymic',
            field=models.CharField(default=0, max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.insurance', verbose_name='Страховое предложение'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='user.companyprofile', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Страховая сумма'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка'),
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
