# Generated by Django 3.2 on 2021-07-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210721_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Страховая сумма'),
        ),
    ]
