# Generated by Django 3.2 on 2021-07-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('main', '0006_alter_insurance_insurance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='user.companyprofile', verbose_name='Компания'),
        ),
    ]
