# Generated by Django 3.2 on 2021-07-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_insurance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Тип страхования'),
        ),
    ]
